# Generated by Django 5.0.4 on 2024-04-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cidade_origem',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pais_origem',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tem_formacao_escolar',
            field=models.BooleanField(default=False),
        ),
    ]
