# Generated by Django 5.0.4 on 2024-04-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_pessoa_acesso_direitos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='acesso_direitos',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='acesso_direitos_assistencia_social',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='acesso_direitos_documentacao_familiares',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='acesso_direitos_educacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='acesso_direitos_outros_apoios_documentacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='acesso_direitos_saude',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='acesso_direitos_trabalho',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='apoio_trabalho_preparo_curriculo_vagas',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='aulas_portugues',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cursos_informatica_tecnologia',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='regularizacao_migratoria',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='area_formacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Formação'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='carteira_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carteira de Trabalho'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade de Residência'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf_valido',
            field=models.BooleanField(default=False, verbose_name='CPF Válido'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de Residência'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='faixa_renda',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faixa de Renda'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nivel_portugues',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nível de Português'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(default='', max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='raca_cor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça/Cor'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='renda_familiar_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Familiar Mensal'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='situacao_laboral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação Laboral'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='status_migratorio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Migratório'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
