# Generated by Django 5.0.4 on 2024-04-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_pessoa_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(default='nome_completo', max_length=100, verbose_name='Nome Completo'),
        ),
    ]
